CREATE DATABASE KHODL_NHTC
USE KHODL_NHTC

CREATE TABLE DIM_NHANVIEN
(
	[MANV] [varchar](10),
	[TENNV] [nvarchar](50),
	[DIENTHOAI] [varchar](10),
	[DIACHI] [nvarchar](100),
	[NGAYSINH] [date],
	[GIOITINH] [nvarchar](3),
	[NGAYVL] [date],

	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
)

CREATE TABLE DIM_MONAN
(
	[MAMON] [varchar](10),
	[TENMON] [nvarchar](50),
	[DONGIA] [float],

	CONSTRAINT PK_MONAN PRIMARY KEY (MAMON)
)

CREATE TABLE DIM_COMBO
(
	MACOMBO VARCHAR(10),
	TENCOMBO NVARCHAR (100),
	GIA FLOAT,

	CONSTRAINT PK_COMBO PRIMARY KEY (MACOMBO)
)

CREATE TABLE DIM_KHUVUC
(
	MAKV VARCHAR(10),
	TENKV NVARCHAR(50),

	CONSTRAINT PK_KHUVUC PRIMARY KEY (MAKV)
)

CREATE TABLE DIM_SANHTIEC
(
	MASANH VARCHAR(10),
	TENSANH NVARCHAR(20),
	SUCCHUA INT,

	CONSTRAINT PK_SANHTIEC PRIMARY KEY (MASANH)
)

CREATE TABLE DIM_NGAYTOCHUC
(
	ID_DATE DATETIME,
	DAY INT,
	MONTH INT,
	YEAR INT,
		
	CONSTRAINT PK_NGAYTOCHUC PRIMARY KEY(ID_DATE)
)
CREATE TABLE DIM_CHITIETCOMBO
	(
		MACOMBO VARCHAR(10),
		MAMON VARCHAR(10),
		SL INT,

		CONSTRAINT PK_CHITIETCOMBO PRIMARY KEY (MACOMBO, MAMON),
	)
CREATE TABLE FACT_DOANHTHU
(
	[MAKV] [VARCHAR](10),
	[MANV] [VARCHAR](10),
	[NGAYTOCHUC] DATETIME,
	[MACOMBO] VARCHAR(10),
	[MASANH] VARCHAR(10),
	[DOANHTHU] FLOAT,
	[SOLUONG] INT,

	CONSTRAINT FK_MAKV FOREIGN KEY (MAKV) REFERENCES DIM_KHUVUC(MAKV),
	CONSTRAINT FK_MANV FOREIGN KEY (MANV) REFERENCES DIM_NHANVIEN(MANV),
	CONSTRAINT FK_NGAYTOCHUC FOREIGN KEY (NGAYTOCHUC) REFERENCES DIM_NGAYTOCHUC(ID_DATE),
	CONSTRAINT FK_MACB FOREIGN KEY (MACOMBO) REFERENCES DIM_COMBO(MACOMBO),
	CONSTRAINT FK_MASANH FOREIGN KEY (MASANH) REFERENCES DIM_SANHTIEC(MASANH)
)

INSERT INTO DIM_KHUVUC
VALUES ('KV001', N'ĐÀ NẴNG')
INSERT INTO DIM_KHUVUC
VALUES ('KV002', N'TP. HCM')
INSERT INTO DIM_KHUVUC
VALUES ('KV003', N'HÀ NỘI')
