	CREATE DATABASE NHTC
	GO
	USE NHTC
	GO

	CREATE TABLE KHUVUC
	(
		MAKV VARCHAR(10),
		TENKV NVARCHAR(50),

		CONSTRAINT PK_KHUVUC PRIMARY KEY (MAKV)
	)

	CREATE TABLE [dbo].[KHACHHANG](
		[MAKH] [int] IDENTITY,
		[TENKH] [nvarchar](100),
		[GIOITINH] [nvarchar](3),
		[DIACHI] [nvarchar](100),
		[DIENTHOAI] [varchar](10),

		CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
	)
	
	CREATE TABLE [dbo].[NHANVIEN](
		[MANV] [varchar](10),
		[TENNV] [nvarchar](50),
		[DIENTHOAI] [varchar](10),
		[DIACHI] [nvarchar](100),
		[NGAYSINH] [date],
		[GIOITINH] [nvarchar](3),
		[NGAYVL] [date],

		CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
	)
	CREATE TABLE LOAIMONAN
	(
		MALOAI VARCHAR(10),
		TENLOAI NVARCHAR(50),

		CONSTRAINT PK_LOAIMONAN PRIMARY KEY (MALOAI)
	)
	CREATE TABLE SANHTIEC
	(
		MASANH VARCHAR(10),
		TENSANH NVARCHAR(20),
		SUCCHUA INT,

		CONSTRAINT PK_SANHTIEC PRIMARY KEY (MASANH)
	)

	CREATE TABLE [dbo].[MONAN](
		[MAMON] [varchar](10),
		[TENMON] [nvarchar](50),
		[DONGIA] [float],
		[MALOAI] [varchar](10)

		CONSTRAINT PK_MONAN PRIMARY KEY (MAMON)
		CONSTRAINT FK_MONAN_LOAIMONAN FOREIGN KEY(MALOAI) REFERENCES LOAIMONAN([MALOAI]),
	)

	CREATE TABLE COMBO
	(
		MACOMBO VARCHAR(10),
		TENCOMBO NVARCHAR (100),
		GIA FLOAT,

		CONSTRAINT PK_COMBO PRIMARY KEY (MACOMBO)
	)

	CREATE TABLE CHITIETCOMBO
	(
		MACOMBO VARCHAR(10),
		MAMON VARCHAR(10),
		SL INT,

		CONSTRAINT PK_CHITIETCOMBO PRIMARY KEY (MACOMBO, MAMON),
		CONSTRAINT FK_CTCB_CB FOREIGN KEY(MACOMBO) REFERENCES COMBO(MACOMBO),
		CONSTRAINT FK_CTCB_MONAN FOREIGN KEY(MAMON) REFERENCES MONAN(MAMON)
	)

	CREATE TABLE NGAYTOCHUC
	(
		ID_DATE DATETIME,
		DAY INT,
		MONTH INT,
		YEAR INT,
		
		CONSTRAINT PK_NGAYTOCHUC PRIMARY KEY(ID_DATE)
	)
	CREATE TABLE DICHVU
	(
		MADV VARCHAR(10),
		TENDV NVARCHAR(50),
		DONGIA FLOAT,
		CONSTRAINT PK_DICHVU PRIMARY KEY (MADV)
	)
	CREATE TABLE UUDAI
	(
		MAUD VARCHAR(10),
		TENUD NVARCHAR(50),
		GHICHU NVARCHAR(100),
		NGAYBD DATE,
		NGAYKT DATE,
		CONSTRAINT PK_UUDAI PRIMARY KEY (MAUD)
	)

	CREATE TABLE PHIEUDATTIEC
	(
		MAPHIEU VARCHAR(10),
		MAKH INT,
		MANV VARCHAR(10),
		MAUD VARCHAR(10),
		KHUVUC VARCHAR(10),
		MASANH VARCHAR(10),
		NGAYDATTIEC DATETIME,
		NGAYTOCHUC DATETIME,
		TIENDATCOC FLOAT,
		TONGTIEN FLOAT,
		
		CONSTRAINT PK_PHIEUDATTIEC PRIMARY KEY (MAPHIEU),
		CONSTRAINT FK_PDT_UD FOREIGN KEY(MAUD) REFERENCES UUDAI(MAUD),
		CONSTRAINT FK_PDT_KH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
		CONSTRAINT FK_PDT_NV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
		CONSTRAINT FK_PDT_KV FOREIGN KEY(KHUVUC) REFERENCES KHUVUC(MAKV),
		CONSTRAINT FK_PDT_NTC FOREIGN KEY(NGAYTOCHUC) REFERENCES NGAYTOCHUC(ID_DATE),
		CONSTRAINT FK_PDT_ST FOREIGN KEY(MASANH) REFERENCES SANHTIEC(MASANH)
	)

	
		
	CREATE TABLE CHITIETPHIEUDATTIEC
	(
		MAPHIEU VARCHAR (10),
		MACOMBO VARCHAR(10),
		SOLUONGBAN INT,
		TENCODAU NVARCHAR(50),
		TENCHURE NVARCHAR (50),

		CONSTRAINT PK_CHITIETPHIEUDATTIEC PRIMARY KEY (MAPHIEU, MACOMBO),
		CONSTRAINT FK_CTPDT_PDT FOREIGN KEY(MAPHIEU) REFERENCES PHIEUDATTIEC(MAPHIEU),
		CONSTRAINT FK_CTPDT_CB FOREIGN KEY(MACOMBO) REFERENCES COMBO(MACOMBO),
	)
	
	CREATE TABLE PHIEUDICHVU
	(
		MAPHIEU VARCHAR (10),
		MADV VARCHAR (10)

		CONSTRAINT PK_PHIEUDICHVU PRIMARY KEY (MAPHIEU, MADV),
		CONSTRAINT FK_PDV_PDT FOREIGN KEY(MAPHIEU) REFERENCES PHIEUDATTIEC(MAPHIEU),
		CONSTRAINT FK_PDV_DV FOREIGN KEY(MADV) REFERENCES DICHVU(MADV),
	)